package rars.custom.callingconvention

enum class CallingConventionErrorType {
    RET_CALLED_WITHOUT_SUBROUTINE,

    GENERAL_REGISTER_READ_BEFORE_WRITE,
    GENERAL_REGISTER_SAVE_AND_LOAD_AMOUNT_NOT_EQUAL,
    GENERAL_REGISTER_WRITE_WITHOUT_READ,

    // CALLEE_SAVE
    CALLEE_SAVE_REGISTER_WRITTEN_BEFORE_SAVING,
    CALLEE_SAVE_REGISTER_WRITTEN_AFTER_RESTORING,
    CALLEE_SAVE_REGISTER_READ_AFTER_RESTORING,
    SHOULD_USE_CALLER_SAVE_INSTEAD_OF_CALLEE_SAVE,
    CALLEE_SAVE_RESTORED_WITHOUT_SAVING,
    CALLEE_SAVE_SAVED_AND_RESTORED_WITHOUT_WRITING,

    // CALLER_SAVE
    CALLER_SAVE_WRITE_AFTER_SAVE,
    CALLER_SAVE_MISSING_SAVE,
    SHOULD_USE_CALLEE_SAVE_INSTEAD_OF_CALLER_SAVE,
    CALLER_SAVE_SAVE_WITHOUT_WRITE,
    CALLER_SAVE_RESTORED_WITHOUT_SAVING,
    CALLER_SAVE_SAVED_AND_RESTORED_WITHOUT_CALLING_FUNCTION,

    RETURN_ADDRESS_REGISTER_MISSING_SAVE
}
