package rars.custom.memory

enum class MemoryErrorType {
    STACK_SHOULD_ONLY_GROW_DOWNWARDS,
    STACK_ONLY_INCREMENTS_OF_4,
    STACK_ONLY_WORD_AS_STORE,
    STACK_STORE_NOT_IN_RESERVED_RANGE,
    STACK_ONLY_WORD_AS_LOAD,
    STACK_LOAD_INVALID_ADDRESS,
    DATA_LOAD_INVALID_ADDRESS,
    DATA_TYPE_MISMATCH,
    STACK_POINTER_DIFFERENT_FROM_START,
    RET_CALLED_WITHOUT_SUBROUTINE,
    STACK_RESERVED_TOO_MUCH_SPACE

}